-- Script para generar datos de prueba: 50 autos, 10 clientes con financiamiento

-- Insertar 10 clientes
INSERT INTO
    "Cliente" (
        "nombre",
        "cedula",
        "telefono",
        "direccion",
        "email",
        "activo",
        "createdAt",
        "updatedAt"
    )
VALUES (
        'Juan Pérez',
        '12345678',
        '091234567',
        'Av. 18 de Julio 1234',
        'juan.perez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'María González',
        '23456789',
        '092345678',
        'Bulevar Artigas 2345',
        'maria.gonzalez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Carlos Rodríguez',
        '34567890',
        '093456789',
        'Av. Italia 3456',
        'carlos.rodriguez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Ana Martínez',
        '45678901',
        '094567890',
        'Av. Brasil 4567',
        'ana.martinez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Luis Fernández',
        '56789012',
        '095678901',
        'Bvar. España 5678',
        'luis.fernandez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Laura Sánchez',
        '67890123',
        '096789012',
        'Av. Agraciada 6789',
        'laura.sanchez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Pedro Ramírez',
        '78901234',
        '097890123',
        'Av. 8 de Octubre 7890',
        'pedro.ramirez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Sofía Torres',
        '89012345',
        '098901234',
        'Rambla República 8901',
        'sofia.torres@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Diego López',
        '90123456',
        '099012345',
        'Av. General Flores 9012',
        'diego.lopez@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Valentina Silva',
        '01234567',
        '091123456',
        'Av. Millán 1234',
        'valentina.silva@email.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Insertar 50 autos (10 financiados + 40 disponibles)
INSERT INTO
    "Auto" (
        "marca",
        "modelo",
        "anio",
        "matricula",
        "precio",
        "estado",
        "activo",
        "clienteId",
        "createdAt",
        "updatedAt"
    )
VALUES
    -- 10 autos financiados (asignados a los 10 clientes)
    (
        'Toyota',
        'Corolla',
        2023,
        'ABC1234',
        25000,
        'financiado',
        true,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Honda',
        'Civic',
        2022,
        'DEF5678',
        28000,
        'financiado',
        true,
        2,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Ford',
        'Focus',
        2023,
        'GHI9012',
        22000,
        'financiado',
        true,
        3,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Chevrolet',
        'Cruze',
        2021,
        'JKL3456',
        24000,
        'financiado',
        true,
        4,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Volkswagen',
        'Golf',
        2023,
        'MNO7890',
        26000,
        'financiado',
        true,
        5,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Nissan',
        'Sentra',
        2022,
        'PQR1234',
        23000,
        'financiado',
        true,
        6,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Hyundai',
        'Elantra',
        2023,
        'STU5678',
        24500,
        'financiado',
        true,
        7,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Mazda',
        '3',
        2022,
        'VWX9012',
        27000,
        'financiado',
        true,
        8,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Peugeot',
        '208',
        2023,
        'YZA3456',
        21000,
        'financiado',
        true,
        9,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'Renault',
        'Logan',
        2021,
        'BCD7890',
        18000,
        'financiado',
        true,
        10,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),

-- 40 autos disponibles (sin cliente)
(
    'Toyota',
    'Yaris',
    2023,
    'EFG1234',
    20000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Honda',
    'Fit',
    2022,
    'HIJ5678',
    19000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Ford',
    'Fiesta',
    2023,
    'KLM9012',
    21000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Chevrolet',
    'Onix',
    2022,
    'NOP3456',
    18500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Volkswagen',
    'Polo',
    2023,
    'QRS7890',
    22000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Nissan',
    'Versa',
    2021,
    'TUV1234',
    17500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Hyundai',
    'i20',
    2023,
    'WXY5678',
    20500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Mazda',
    '2',
    2022,
    'ZAB9012',
    19500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Peugeot',
    '2008',
    2023,
    'CDE3456',
    28000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Renault',
    'Sandero',
    2022,
    'FGH7890',
    16500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Toyota',
    'RAV4',
    2023,
    'IJK1234',
    35000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Honda',
    'CR-V',
    2022,
    'LMN5678',
    38000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Ford',
    'Escape',
    2023,
    'OPQ9012',
    32000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Chevrolet',
    'Tracker',
    2021,
    'RST3456',
    30000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Volkswagen',
    'Tiguan',
    2023,
    'UVW7890',
    40000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Nissan',
    'Kicks',
    2022,
    'XYZ1234',
    27000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Hyundai',
    'Tucson',
    2023,
    'ABC5678',
    36000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Mazda',
    'CX-5',
    2022,
    'DEF9012',
    39000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Peugeot',
    '3008',
    2023,
    'GHI3456',
    42000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Renault',
    'Duster',
    2021,
    'JKL7890',
    25000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Toyota',
    'Hilux',
    2023,
    'MNO1234',
    45000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Ford',
    'Ranger',
    2022,
    'PQR5678',
    48000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Chevrolet',
    'S10',
    2023,
    'STU9012',
    46000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Nissan',
    'Frontier',
    2021,
    'VWX3456',
    42000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Volkswagen',
    'Amarok',
    2023,
    'YZA7890',
    50000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Fiat',
    'Cronos',
    2022,
    'BCD1234',
    17000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Fiat',
    'Argo',
    2023,
    'EFG5678',
    18000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Fiat',
    'Toro',
    2022,
    'HIJ9012',
    35000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Jeep',
    'Compass',
    2023,
    'KLM3456',
    45000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Jeep',
    'Renegade',
    2021,
    'NOP7890',
    38000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Suzuki',
    'Swift',
    2023,
    'QRS1234',
    19500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Suzuki',
    'Vitara',
    2022,
    'TUV5678',
    28500,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Kia',
    'Rio',
    2023,
    'WXY9012',
    20000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Kia',
    'Sportage',
    2022,
    'ZAB3456',
    37000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Mitsubishi',
    'L200',
    2023,
    'CDE7890',
    47000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Mitsubishi',
    'ASX',
    2021,
    'FGH1234',
    32000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Subaru',
    'Impreza',
    2023,
    'IJK5678',
    33000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Subaru',
    'XV',
    2022,
    'LMN9012',
    36000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Citroën',
    'C3',
    2023,
    'OPQ3456',
    19000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Citroën',
    'C4',
    2021,
    'RST7890',
    24000,
    'disponible',
    true,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- Crear planes de cuotas para cada uno de los 10 clientes (12 cuotas cada uno)
-- Cliente 1 - Juan Pérez (Auto 1: Toyota Corolla $25000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        1,
        1,
        2083.33,
        '2025-01-15',
        '2025-01-10',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        2,
        2083.33,
        '2025-02-15',
        '2025-02-12',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        3,
        2083.33,
        '2025-03-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        4,
        2083.33,
        '2025-04-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        5,
        2083.33,
        '2025-05-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        6,
        2083.33,
        '2025-06-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        7,
        2083.33,
        '2025-07-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        8,
        2083.33,
        '2025-08-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        9,
        2083.33,
        '2025-09-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        10,
        2083.33,
        '2025-10-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        11,
        2083.33,
        '2025-11-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        12,
        2083.37,
        '2025-12-15',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 2 - María González (Auto 2: Honda Civic $28000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        2,
        1,
        2333.33,
        '2025-01-20',
        '2025-01-18',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        2,
        2333.33,
        '2025-02-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        3,
        2333.33,
        '2025-03-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        4,
        2333.33,
        '2025-04-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        5,
        2333.33,
        '2025-05-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        6,
        2333.33,
        '2025-06-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        7,
        2333.33,
        '2025-07-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        8,
        2333.33,
        '2025-08-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        9,
        2333.33,
        '2025-09-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        10,
        2333.33,
        '2025-10-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        11,
        2333.33,
        '2025-11-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        12,
        2333.37,
        '2025-12-20',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 3 - Carlos Rodríguez (Auto 3: Ford Focus $22000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        3,
        1,
        1833.33,
        '2025-01-25',
        '2025-01-22',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        2,
        1833.33,
        '2025-02-25',
        '2025-02-20',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        3,
        1833.33,
        '2025-03-25',
        '2025-03-22',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        4,
        1833.33,
        '2025-04-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        5,
        1833.33,
        '2025-05-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        6,
        1833.33,
        '2025-06-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        7,
        1833.33,
        '2025-07-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        8,
        1833.33,
        '2025-08-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        9,
        1833.33,
        '2025-09-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        10,
        1833.33,
        '2025-10-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        11,
        1833.33,
        '2025-11-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        12,
        1833.37,
        '2025-12-25',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 4 - Ana Martínez (Auto 4: Chevrolet Cruze $24000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        4,
        1,
        2000.00,
        '2025-01-10',
        '2025-01-08',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        2,
        2000.00,
        '2025-02-10',
        NULL,
        'vencido',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        3,
        2000.00,
        '2025-03-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        4,
        2000.00,
        '2025-04-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        5,
        2000.00,
        '2025-05-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        6,
        2000.00,
        '2025-06-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        7,
        2000.00,
        '2025-07-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        8,
        2000.00,
        '2025-08-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        9,
        2000.00,
        '2025-09-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        10,
        2000.00,
        '2025-10-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        11,
        2000.00,
        '2025-11-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        12,
        2000.00,
        '2025-12-10',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 5 - Luis Fernández (Auto 5: Volkswagen Golf $26000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        5,
        1,
        2166.67,
        '2025-01-12',
        NULL,
        'vencido',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        2,
        2166.67,
        '2025-02-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        3,
        2166.67,
        '2025-03-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        4,
        2166.67,
        '2025-04-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        5,
        2166.67,
        '2025-05-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        6,
        2166.67,
        '2025-06-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        7,
        2166.67,
        '2025-07-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        8,
        2166.67,
        '2025-08-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        9,
        2166.67,
        '2025-09-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        10,
        2166.67,
        '2025-10-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        11,
        2166.67,
        '2025-11-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        12,
        2166.63,
        '2025-12-12',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 6 - Laura Sánchez (Auto 6: Nissan Sentra $23000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        6,
        1,
        1916.67,
        '2025-01-18',
        '2025-01-15',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        2,
        1916.67,
        '2025-02-18',
        '2025-02-16',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        3,
        1916.67,
        '2025-03-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        4,
        1916.67,
        '2025-04-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        5,
        1916.67,
        '2025-05-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        6,
        1916.67,
        '2025-06-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        7,
        1916.67,
        '2025-07-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        8,
        1916.67,
        '2025-08-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        9,
        1916.67,
        '2025-09-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        10,
        1916.67,
        '2025-10-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        11,
        1916.67,
        '2025-11-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        12,
        1916.63,
        '2025-12-18',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 7 - Pedro Ramírez (Auto 7: Hyundai Elantra $24500)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        7,
        1,
        2041.67,
        '2025-01-22',
        '2025-01-20',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        2,
        2041.67,
        '2025-02-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        3,
        2041.67,
        '2025-03-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        4,
        2041.67,
        '2025-04-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        5,
        2041.67,
        '2025-05-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        6,
        2041.67,
        '2025-06-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        7,
        2041.67,
        '2025-07-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        8,
        2041.67,
        '2025-08-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        9,
        2041.67,
        '2025-09-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        10,
        2041.67,
        '2025-10-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        11,
        2041.67,
        '2025-11-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        12,
        2041.63,
        '2025-12-22',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 8 - Sofía Torres (Auto 8: Mazda 3 $27000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        8,
        1,
        2250.00,
        '2025-01-05',
        '2025-01-03',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        2,
        2250.00,
        '2025-02-05',
        '2025-02-04',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        3,
        2250.00,
        '2025-03-05',
        '2025-03-03',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        4,
        2250.00,
        '2025-04-05',
        '2025-04-02',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        5,
        2250.00,
        '2025-05-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        6,
        2250.00,
        '2025-06-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        7,
        2250.00,
        '2025-07-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        8,
        2250.00,
        '2025-08-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        9,
        2250.00,
        '2025-09-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        10,
        2250.00,
        '2025-10-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        11,
        2250.00,
        '2025-11-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        12,
        2250.00,
        '2025-12-05',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 9 - Diego López (Auto 9: Peugeot 208 $21000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        9,
        1,
        1750.00,
        '2025-01-08',
        NULL,
        'vencido',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        2,
        1750.00,
        '2025-02-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        3,
        1750.00,
        '2025-03-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        4,
        1750.00,
        '2025-04-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        5,
        1750.00,
        '2025-05-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        6,
        1750.00,
        '2025-06-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        7,
        1750.00,
        '2025-07-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        8,
        1750.00,
        '2025-08-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        9,
        1750.00,
        '2025-09-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        10,
        1750.00,
        '2025-10-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        11,
        1750.00,
        '2025-11-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9,
        12,
        1750.00,
        '2025-12-08',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Cliente 10 - Valentina Silva (Auto 10: Renault Logan $18000)
INSERT INTO
    "Pago" (
        "autoId",
        "numeroCuota",
        "monto",
        "fechaVencimiento",
        "fechaPago",
        "estado",
        "createdAt",
        "updatedAt"
    )
VALUES (
        10,
        1,
        1500.00,
        '2025-01-28',
        '2025-01-26',
        'pagado',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        2,
        1500.00,
        '2025-02-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        3,
        1500.00,
        '2025-03-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        4,
        1500.00,
        '2025-04-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        5,
        1500.00,
        '2025-05-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        6,
        1500.00,
        '2025-06-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        7,
        1500.00,
        '2025-07-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        8,
        1500.00,
        '2025-08-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        9,
        1500.00,
        '2025-09-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        10,
        1500.00,
        '2025-10-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        11,
        1500.00,
        '2025-11-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        10,
        12,
        1500.00,
        '2025-12-28',
        NULL,
        'pendiente',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Verificar resultados
SELECT 'Clientes creados:' as tipo, COUNT(*) as total FROM "Cliente";

SELECT 'Autos creados:' as tipo, COUNT(*) as total FROM "Auto";

SELECT 'Autos financiados:' as tipo, COUNT(*) as total
FROM "Auto"
WHERE
    estado = 'financiado';

SELECT 'Autos disponibles:' as tipo, COUNT(*) as total
FROM "Auto"
WHERE
    estado = 'disponible';

SELECT 'Pagos creados:' as tipo, COUNT(*) as total FROM "Pago";

SELECT 'Pagos pagados:' as tipo, COUNT(*) as total
FROM "Pago"
WHERE
    estado = 'pagado';

SELECT 'Pagos pendientes:' as tipo, COUNT(*) as total
FROM "Pago"
WHERE
    estado = 'pendiente';

SELECT 'Pagos vencidos:' as tipo, COUNT(*) as total
FROM "Pago"
WHERE
    estado = 'vencido';